apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    course: "DevOps"
    trainer: "SivaKumar_R"      
spec:
  containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux
     command: ["sleep", "100000"]