apiVersion: v1
kind: Pod
metadata:
  name: resource_limiting
  labels:
    course: "DevOps"
    trainer: "SivaKumar_R"
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests: # soft limit
        memory: "68Mi"
        cpu: "100m"
      limits: # hard limit
        memory: "128Mi"
        cpu: "150m"
    