apiVersion: v1
kind: Pod
metadata:
 name: pod-config
 labels:
  course: "DevOps"
  trainer: "SivaKumar_R"
spec:
 containers:
  - name: nginx
    image: nginx
    envFrom:
     - configMapRef:
        name: config-map