apiVersion: v1
kind: Pod
metadata:
 name: pod_config
 labels:
  course: "DevOps"
  trainer: "SivaKumar_R"
spec:
 containers:
  - name: nginx
    image: nginx
    env:
     valueFrom:
      configMapKeyRef:
       - name: config_map