apiVersion: v1
kind: Service
metadata:
  name: service
  labels: 
    purpose: service-demo
spec:
  selector: 
    purpose: service-demo
    environment: dev
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 #service port 
      targetPort: 80  # container port

---
apiVersion: v1
kind: Pod
metadata: 
  name: service-pod
  labels:
    purpose: service-demo
    environment: dev
    project: roboshop
spec:
  containers:
    - name: nginx
      image: nginx
       